version: "2.1"

services:
  database:
    image: mariadb
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
    volumes:
      - "./etc/database/data:/var/lib/mysql"
      - "./etc/database:/docker-entrypoint-initdb.d"

  server:
    depends_on:
        - database
    container_name: server
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
      - PORT=3000
      - SOCKETS_PORT=8443
    build:
      context: .
      dockerfile: server/Dockerfile
    command: "npm run start"
    volumes:
      - ./server:/var/www/server
    ports:
        - 8443:8443

  nginx:
    depends_on:
        - client
        - server
    build: ./etc/nginx
    volumes:
      - ./client:/var/www/client
    ports:
        - 8082:80
        - 8083:443

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/var/www/client
    depends_on:
      - server